### PR TITLE
Tell renovate not to pin dependencies

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Review by eoinkelly — APPROVED** [review]
👍

**Comment by Br3nda** [comment]
i don't understand why this change makes that test fail

**Comment by Br3nda** [comment]
```ruby
  describe '#all_sources_present?' do
    subject { helper.all_sources_present?(page) }

    context 'all sources are present' do
      it 'returns true' do
        expect(subject).to be true
      end
    end

```

results in 
```
Failures:
  1) PagesHelper#all_sources_present? all sources are present returns true
     Failure/Error: expect(subject).to be true
     
       expected true
            got false
     # ./spec/helpers/pages_helper_spec.rb:18:in `block (4 levels) in <top (required)>'
```

**Comment by eoinkelly** [comment]
I had a look - here's the story:

That test will fail if the `S3_BUCKET_URL` env var is blank. That env var is set in the Travis settings but for some reason it doesn't seem to be exported into the environment for your branch

This is a snippet of the build output from `staging`:
```
Setting environment variables from repository settings
$ export NZSL_ONLINE_SECRET_KEY_BASE=81f5b67f427fd1f2f59cca93a6de3446eed12a3e75b2adf43bdec71b9bb0a55d30ce8b9debd14b252d30760548bb69a86a10f7b486c7b7634617eab69f168f52
$ export CC_TEST_REPORTER_ID=[secure]
$ export APP_DOMAIN_NAME=localhost:3000
$ export APP_PROTOCOL=http
$ export S3_BUCKET_URL=[secure]
```

and this is the same snippet from your branch
```
Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
Setting environment variables from repository settings
$ export NZSL_ONLINE_SECRET_KEY_BASE=81f5b67f427fd1f2f59cca93a6de3446eed12a3e75b2adf43bdec71b9bb0a55d30ce8b9debd14b252d30760548bb69a86a10f7b486c7b7634617eab69f168f52
$ export APP_DOMAIN_NAME=localhost:3000
$ export APP_PROTOCOL=http
```

https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions explains what is happening - currently we have `CC_TEST_REPORTER_ID` and `S3_BUCKET_URL` set as encrypted env vars so Travis won't push them into the environment of a fork. 

`S3_BUCKER_URL` is just a dummy string anyway so I think we are fine to make it an unencrypted env var but I think `CC_TEST_REPORTER_ID` (which identifies us to CodeClimate) should stay private.

I have set `S3_BUCKET_URL` to `http://s3-ap-southeast-2.amazonaws.com/dummy-fake/` in Travis settings which should hopefully fix your build.

**Pull request merged**
