### PR TITLE
Release 24

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Comment by DSRU** [comment]
@Br3nda not sure if I'm the appropriate person to review these kind of changes? I have no idea what I would be looking for.

**Review by eoinkelly — APPROVED** [review]

**Comment by Br3nda** [comment]
@dsru I'd like to know that you're okay with us continuing to release these changes. Often there's a feature and I'd really like you to stay in control by approving before they go live.
If you go to "changes" tab and choose "approve" I'll know you're not going to get a suprise that we released something.

When it's a security patch we likely wont wait for approval. But all other changes it would be ideal to have @dsru always aware that we're changing things.

**Comment by Br3nda** [comment]
Having said that, this proposed release is css clean up and reducing log verbosity. No new features.

**Comment by DSRU** [comment]
@Br3nda ok, I'll just approve these then if I don't see anything that rings alarm bells in terms of changing how the site functions; but often I won't understand what it is I'm approving, so I might still be surprised :-)

**Review by DSRU — APPROVED** [review]

**Pull request merged**
