### PR TITLE
Release 9. paperclip hotpatch

### PR DESCRIPTION
**Pull request by Br3nda**
Wait for #128 then release

### CODE REVIEW

**Comment by Br3nda** [comment]
@elspeth-rabid is CD hooked up on this repo?

**Comment by Br3nda** [comment]
I answered my own question.. yes CD is all good.

**Comment by joshmcarthur** [comment]
Nice @Br3nda - I was just about to open an issue to ask how production deploys happen :-)

**Comment by Br3nda** [comment]
Closed and re-opened, because travis didn't trigger.

**Comment by Br3nda** [comment]
I RELEASED THE KRAKKEN....
also the paperclip hotfix.

**Pull request merged**
