### PR TITLE
Release 16 (rails 5 to production)

### PR DESCRIPTION
**Pull request by Br3nda**
promoting to production

### CODE REVIEW

**Comment by Br3nda** [comment]
@Rabid-Dan Leaving for you to test and give the word

**Comment by Rabid-Dan** [comment]
🌟 Thanks @Br3nda we'll probably look at targeting a production deploy toward the end of this week or the start of next but ill let you know when its good to go!

**Review by Rabid-Dan — APPROVED** [review]
@Br3nda We've got the thumbs up to deploy all of the changes in here now. Would it be possible to get it rolled out tomorrow at some point?

**Comment by elspeth-rabid** [comment]
I am going to merge this on @Rabid-Dan's request

**Review by elspeth-rabid — APPROVED** [review]

**Pull request merged**
