### PR TITLE
Add user agents to robots.txt

### PR DESCRIPTION
**Pull request by louise-r-blue**

### CODE REVIEW

**Comment by louise-r-blue** [comment]
The User agents listed in the robot.txt file have been detailed in the Raygun HTTP tab as looking for the urls `ads.txt` and `app-ads.txt`. These urls do not exist. The product owner wishes for this search to be disallowed.

**Review by vinithanatarajan — APPROVED** [review]

**Review by Rabid-Dan — CHANGES_REQUESTED** [review]
Have already discussed in person but we can avoid the need for specific user agents here by just keeping the catch all * at the top and then only having a single entry for each file to disallow.

**Comment by louise-r-blue** [comment]
thanks @Rabid-Dan have made the change

**Review by Rabid-Dan — APPROVED** [review]

**Comment by Br3nda** [comment]
Is there more info on what is requesting these files?

**Comment by Br3nda** [comment]
i think the file is supposed to be called `robots.txt`.
Is `robot.txt` a mistake, or is it a new thing i've not heard of. ?

**Comment by Br3nda** [comment]
nvm, the file name is correct -- only the git commit message is the wrong file name

**Comment by louise-r-blue** [comment]
@Br3nda thanks for spotting the incorrect spelling. I will collate some of the errors I have come across in raygun where the user agent is a web crawler or bot and paste examples in this pr.

**Comment by louise-r-blue** [comment]
@Br3nda I won't merge anything until I paste in some example errors.

**Comment by louise-r-blue** [comment]
@Br3nda I am closing this PR as Eoin has made better changes in #477 and #476

**Pull request closed without merging**
