### PR TITLE
Bug/add vocab sheet name to print view

### PR DESCRIPTION
**Pull request by KatieWright26**
Fixing bug from [here](https://www.pivotaltracker.com/story/show/152022215). Have added the title of a users Vocab Sheet to the print preview and printed page views. Made some minor tweaks to styles to center vocab cards on printed sheet and align with title.

screen shot 2018-01-25 at 10 59 27 am
screen shot 2018-01-25 at 10 59 39 am

### CODE REVIEW

**Comment by Br3nda** [comment]
@KatieWright26 would you like me to merge this while i'm here?

**Comment by KatieWright26** [comment]
Yes please! - I don't have access to merge as a contributor

**Comment by Br3nda** [comment]
I've invited you to the ORG.

Let's get the paperclip hotpatch out to prod before we push this pr into the staging branch.

**Comment by Br3nda** [comment]
Released. @joshmcarthur is looking at the CD - so it should be on staging shortly

**Pull request merged**
