### PR TITLE
Add staging environment

### PR DESCRIPTION
**Pull request by Rabid-Dan**
The new save as PDF work requires an app domain name and protocol which are stored against the environment in the secrets file. I think this is causing issues on staging because while settings exist for staging in a bunch of places, staging just uses the production settings instead.

This branch adds a staging env file as part of the process of changing that over. 
With how everything else is configured it looks like the only thing that should change after deployment is those secrets items.

### CODE REVIEW

**Review by ghostPepperWonton — APPROVED** [review]

**Review by elspeth-rabid — APPROVED** [review]

**Comment by elspeth-rabid** [comment]
@joshmcarthur just made the valid point that heroku uses the production rails environment, always.

**Review by vinithanatarajan — APPROVED** [review]

**Comment by Rabid-Dan** [comment]
oooooh @elspeth-rabid will this not do what I want it to do then? I could probably change the items that are stored in the secrets file to just be straight environment variables and save them in the heroku config variables instead

**Comment by elspeth-rabid** [comment]
@Rabid-Dan yeah I think that is the Heroku way.

**Comment by Rabid-Dan** [comment]
rad! thanks for the heads up. I'm gonna close this one and open up a new one to do that instead

**Pull request closed without merging**
