### PR TITLE
Production release

### PR DESCRIPTION
**Pull request by Br3nda**
This release fixes autocomplete

### CODE REVIEW

**Review by DSRU — COMMENTED** [review]
I'm ready to approve the autocomplete changes, but this production release also includes the caching of the numbers page and 'sign of the day', which I'm still testing. So I'll hold off on approving until that has happened.

**Comment by eoinkelly** [comment]
I saw a caching error on staging this morning which I haven't been able to replicate locally yet so can we hold on this deploy until I have figured out what is happening.

**Comment by eoinkelly** [comment]
Once PR #584 lands this should be good to go I think

**Comment by DSRU** [comment]
Looking good on staging but the numbers page images load a lot slower than they do on the current site. Is this just because of the staging environment?

**Comment by eoinkelly** [comment]
@DSRU Yes staging does not use the CDN so loading images is slow

**Review by DSRU — APPROVED** [review]

**Review by eoinkelly — APPROVED** [review]

**Comment by eoinkelly** [comment]
I'm going to merge this now. I'm available to deal with any issues which arise.

**Pull request merged**
