### PR TITLE
Release 21

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Review by Rabid-Dan — APPROVED** [review]

**Review by louise-r-blue — APPROVED** [review]
Looks good : }

**Comment by Br3nda** [comment]
Has anyone tested on staging? I'm thinking a Friday release is a bad luck idea, and better to wait for @jakerabid on Monday - and someone needs to verify it's doing the new logging on staging before we put this live.

**Comment by Rabid-Dan** [comment]
@Br3nda I completely agree with that, its got the ticks to be merged but it would be massively useful for @jakerabid to be around in the event that anything bad happens (I'm also generally pretty averse to Friday prod deployments)

**Comment by JacobBriggsAckama** [comment]
@Br3nda @Rabid-Dan I do not have access to the heroku for the staging nzsl site, so I am unable to test that the extra logging works. I do not think I have access to the front end nzsl-staging.heroku.com in order to make the logs either

**Comment by Br3nda** [comment]
I don't have access to heroku either it's on the Rabid account.
Are you sure you don't have access Jake? Are you still at Rabid?

**Comment by Br3nda** [comment]
i've emailed you more info @jakerabid

**Comment by JacobBriggsAckama** [comment]
Some of the extra logging will only work in prod - the change to /config/environments/production.rb where I added `config.log_tags = [:request_id]`
The rest I haven't seen in the logs even though I browsed the site. It only logs when `write_file_locally` is called and does the staging site even clean up the images at all meaning they need to be retrieved again?

**Comment by Br3nda** [comment]
Oic. Does our staging server not use the production.rb?

**Comment by Br3nda** [comment]
I had a look, and staging is using production.rb

**Comment by JacobBriggsAckama** [comment]
In that case, `config.log_tags = [:request_id]` doesn't seem to change the logging output. It doesn't seem to break it either though....

**Comment by Br3nda** [comment]
@jakerabid if you need to test the logging change further, heroku lets you make a new app for free, and deploy your own branch to it.

**Comment by JacobBriggsAckama** [comment]
oh wow I didn't know about "review apps" on heroku, this is pretty cool :)

**Comment by JacobBriggsAckama** [comment]
Okay so I figured out that the staging server for some reason wasn't autodeploying which is why the logging wasn't working. I manually started the deploy, and the logging change is showing up, so once I work out why travis isn't working we can get this merged!

**Comment by Br3nda** [comment]
I don't have access to the herokus anymore - so I can't look at this one.

**Comment by Br3nda** [comment]
@jakerabid there's a security patch in hwre now, that needs deployment. Can you check thar staging is deploying and the latest change hasnt broken it.

**Comment by louise-r-blue** [comment]
@Br3nda is this ready to deploy to Prod? : } or should we wait till the new year?

**Comment by Br3nda** [comment]
I don't know. We need someone with heroku access to check it deployed to staging, and the new logging by jake caused no issues. Rabid are the only people woth access to check this.

There's a security patch in here so it is now urgent.

**Comment by louise-r-blue** [comment]
@Br3nda Jake had to manually get the deploy to staging yesterday in Heroku and all went well.. Micky has tested staging and has ok'd. Elspeth is on holiday and you are the only other authorised to merge to master . When  you merge to master we will deploy to production in Heroku.
I am 99.9% certain everything will be fine : }

**Pull request merged**
