### PR TITLE
Auto corrected by following Lint Ruby MagicComment

### PR DESCRIPTION
**Pull request by Br3nda**
Auto corrected by following Lint Ruby MagicComment

Click [here](https://awesomecode.io//repos/ODNZSL/nzsl-online/config_groups/ruby/188) to configure it on awesomecode.io

### CODE REVIEW

**Review by eoinkelly — APPROVED** [review]

**Comment by eoinkelly** [comment]
CodeFactor wants me to use unary + to make a mutable string - that is pretty opaque syntax so my view is CodeFactor is wrong here. I can't resolve it in CodeFactor :shrug:

**Comment by eoinkelly** [comment]
@Br3nda CodeFactor seems to be running Rubocop under the hood (a different version with different settings to what codeclimate runs). I think we need to have just one version of rubocop running or we'll have a lot of busy work to do - do we need both CodeFactor **and** CodeClimate?

**Comment by Br3nda** [comment]
Agreed. Let's turn off code factor

**Comment by eoinkelly** [comment]
Sweet. I have removed the Codefactor webhook.

**Pull request merged**
