### PR TITLE
Release 13

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Review by elspeth-rabid — DISMISSED** [review]

**Comment by Br3nda** [comment]
Looks good on staging for me.
Do you want to push the button to merge/deploy @elspeth-rabid  ?

**Comment by elspeth-rabid** [comment]
@Br3nda - I am surprised the frontend is OK with that Foundation bump.
I think I will have to take a more in depth look around before deploying.

**Comment by Br3nda** [comment]
There was a PR  while back where I flagged that assets aren't rebuilt in deploy. It might be still running the old but assets.

**Comment by Br3nda** [comment]
@elspeth-rabid do you need any more time? Can we release this?

**Review by elspeth-rabid — APPROVED** [review]
Sorry for being so slow :-(

**Comment by Br3nda** [comment]
we have 4 failing tests. They look like network calls that are not mocked. We can fi those before we release that.

**Comment by Br3nda** [comment]
@danieljauch are you happy for your recent changes to go to production?

**Pull request merged**
