### PR TITLE
Updated feature for removing video controls. 

### PR DESCRIPTION
**Pull request by louise-r-blue**
In response to Dan's comments I am updating this PR comment/description.

This is for the NZSL-35 user story where the client has asked that some of the video controls be removed or altered so as not to obscure the user from viewing the video.

- This PR is in response to the client requesting that only the 'shorter' top gloss video be kept on a loop. The usage and translation videos are typically longer and looping them is not required.
- A preload attribute was also updated for consistency.
- I also updated my branch to bring it up to date with the base branch in this PR.

### CODE REVIEW

**Review by ghostPepperWonton — APPROVED** [review]

**Comment by Rabid-Dan** [comment]
Will this do what you think it will do? 
You've said that it will make a shorter top video but surely setting loop to true will create a longer video because it will just continue to play over and over until it stops?

Also this is an more of a request for the future, but some extra context in the description and a PR title that is more descriptive than just the branch name is suuuuper helpful for reviewers and can help to avoid questions like this.
Our standards for PRs are here https://github.com/ackama/wiki/wiki/Pull-Request-Review#requesting-a-review (specifically the writing a review bit will be useful here)

**Comment by louise-r-blue** [comment]
@Rabid-Dan Thanks for the review. When I said shorter I meant that the top gloss video is typically shorter than the usage and translation videos. Micky has asked for the top gloss video to be put on a loop (she posted in public nzsl yesterday '... If there is an option to only have the full screen control (without timestamp etc) that would be ideal. The loop should be on the gloss video (the short one at the top) but ideally switched off for the usage videos (the longer signed sentences...'

**Review by Rabid-Dan — APPROVED** [review]

**Comment by Rabid-Dan** [comment]
@louise-r-blue thanks for the extra context, I've checked this out locally and approved now

**Comment by louise-r-blue** [comment]
hold off merging please Lou

**Pull request merged**
